### ISSUE TITLE
"Sign in with GitHub" opens new browser window  instead of authenticating the original window.

### ISSUE THREAD

**Issue by KargJonas** [o2sh/codl#2]
Browser: Chrome 73.0.3683.86 (Official Build) (64-bit)
OS: Ubuntu 18.04.8

Expected behavior: Clicking the GitHub login Button opens a new window with the GitHub auth-page.
What happens: New authenticated window is opened with a locked address bar.

PS: It would be nice if users could stay logged in.

**Comment by o2sh** [comment]
Hi @KargJonas,
I'm not sure I'm following you, when you try to login (click on Github login button) a popup window opens with the site in it ?

If that's the case, make sure you're accessing the app through https ?

Sorry, if I misunderstood.

**Comment by KargJonas** [comment]
Yup - works on https.
Still, the app seems to behave incorrectly on http but that's probably due to github auth not allowing it.
Tried on my other machine (same setup), there the redirect works but not on this machine.
Do you use serverside redirects?

Besides that - it's looking and working great :smile:

**Comment by o2sh** [comment]
Ok cool, I definetly should block http or at least make sure it redirects to https (which should happen by default with .dev sites). The redirect is handled by github OAuth API.

Thanks for the feedback @KargJonas

**Comment by o2sh** [comment]
The redirection (HTTP --> HTTPS) should be working now

**Comment by KargJonas** [comment]
Nice!

**Comment by KargJonas** [comment]
Yup it's working!
