### ISSUE TITLE
Add Reply to Comment feature

### ISSUE THREAD

**Issue by o2sh** [o2sh/codl#3]
Currently, our users can post new comments but are not able to reply to existing ones.

This feature is terribly missing... and should  impact all layers of the App (back, front, and DB)

The stack is quite standard: React + Spring(Java) +MySql

Feel free to ask any question :wink: 

Have fun!!

The site is live --> https://codl.dev

**Comment by joelibaceta** [comment]
The site is down now :c 

<img width="397" alt="Captura de Pantalla 2019-09-30 a la(s) 17 13 13" src="https://user-images.githubusercontent.com/864790/65920763-975bde00-e3a5-11e9-96c8-35ad9aa20a60.png">

**Comment by o2sh** [comment]
mmmh, weird!
Everything seems OK on my side.

Do you get the error right after clicking on the link ? what is your browser ?
